### ISSUE TITLE
Music don't resume playing if intermission was paused

### ISSUE THREAD

**Issue by JNechaevsky** [Russian-Doom/russian-doom#69]
Steps to reproduce:

- Finish any level to make an intermission screen appear.
- Pause the game while in intermission screen.
- Press any key to start a next level (yes, while pause is still on).
- New level will start with locked up first musical note (♫).

It's a bug of Chocolate Doom, in vanilla music will play normally.

@fabiangreffrath, Crispy is also affected.

**Comment by JNechaevsky** [comment]
As a workaround, it is possible to put `S_ResumeSound();` into `G_DoLoadLevel`. It will fix this bug, but something definitely not right somewhere else...

**Comment by fabiangreffrath** [comment]
Looks like the game isn't properly unpaused. Why is it even possible to move on the the next level from the intermission screen when the game is paused?

**Comment by fabiangreffrath** [comment]
> As a workaround, it is possible to put S_ResumeSound(); into G_DoLoadLevel.

Doesn't look that wrong. After all, that's the first thing that gets called in `G_InitNew()`.

**Comment by JNechaevsky** [comment]
> Why is it even possible to move on the the next level from the intermission screen when the game is paused?

Looks likes game accepts typing/skipping keys if intermission screen is paused, and this is leading to loading new level. I'll try to check DOS code deeply, since it is not affected by this bug, but if you are recommending to use `S_ResumeSound`, I'd better use it. :)

**Comment by JNechaevsky** [comment]
This bug is also suspiciously similar to few others, that I had fixed in Heretic and Hexen: https://github.com/JNechaevsky/russian-doom/commit/9d2a24a30251ba4812daaf36b1a2676d7541e8d3 and https://github.com/JNechaevsky/russian-doom/commit/20b73cb7d10890a42ad580efdf64334269b19120. But those ones was a vanilla bugs.

**Comment by fabiangreffrath** [comment]
> if you are recommending to use S_ResumeSound, I'd better use it

It's not a recommendation (yet), just a statement that it's already used elsewhere. ;)

**Comment by JNechaevsky** [comment]
Ah, okay then! I think there are three ways to solve this issue:

1. Game should be properly paused, if it is paused in intermission screen and no skipping keys should by accepted. Non-vanilla and more logically correct behavior _(preffered!)_
2. Game should properly resume music after intermission screen was paused and skipped. `S_ResumeSound` will fix it. Correct vanilla behavior.
3. Discover what's wrong initially, to make it behave like vanilla.

**Comment by JNechaevsky** [comment]
Just thought that approach №1 can be very unsafe for demos, since pause is also always recording. AFAIR, I have seen some pausing in intermission screen right while watching Archvile's `actor->y` correction.

**Comment by JNechaevsky** [comment]
Oh :boom:, this bug is even worse when Native MIDI is selected. Steps to reproduce, it's same for RD and Crispy, when there is no `midiproc.exe` used.

- Select System MIDI in setup and start the game
- Finish the level and press `pause` while still on intermission screen
- Press any key to go to next level
- There will no be any sound music
- Okay, now exit the game and start it again
- Still no sound until... `pause` is pressed two times.

Fortunately, this approach helps:

```
void G_DoLoadLevel (void) 
{ 
    int i; 

+++ if (paused)
+++ {
+++     paused = false;
+++     S_ResumeSound ();
+++ }

    // Set the sky map.
```

Something deffinitly not right deep inside of ... something. Could it be a `pcsound`?

**Comment by JNechaevsky** [comment]
I decided to apply two approaches:

**1.** Pause will now work properly on intermission screen (in all the games): https://github.com/JNechaevsky/russian-doom/commit/b61fefc4b54e392acef995030ddf80bf6bd06b2b
**2.** If paused, game will be unpaused and `S_ResumeSound` will be called in `G_DoLoadLevel`: https://github.com/JNechaevsky/russian-doom/commit/d79232371ad6ebeaa66d0de55e04d14dbc7a9df4

Guess this is more than good enough.

**Comment by fabiangreffrath** [comment]
Yep, seems like this is caused by unconditionally resetting the `paused` variable in `G_DoLoadLevel()` without taking account of the music. I think I will apply the following patch to Crispy:
```
--- a/src/doom/g_game.c
+++ b/src/doom/g_game.c
@@ -816,6 +816,10 @@ void G_DoLoadLevel (void)

     // clear cmd building stuff

+    if (paused)
+    {
+       S_ResumeSound();
+    }
     memset (gamekeydown, 0, sizeof(gamekeydown));
     joyxmove = joyymove = joystrafemove = joylook = 0;
     mousex = mousey = 0;
```

@JNechaevsky You said this was a bug in Choco that's not present in Vanilla? So... would you mind filing a PR with all the information you've got so far?

**Comment by fabiangreffrath** [comment]
How about muted music (volume = 0)? Do we have to take this into account as well?

```
--- a/src/doom/g_game.c
+++ b/src/doom/g_game.c
@@ -816,6 +816,12 @@ void G_DoLoadLevel (void)

     // clear cmd building stuff

+    if (paused && musicVolume)
+    {
+       paused = false;
+       S_ResumeSound();
+    }
+
     memset (gamekeydown, 0, sizeof(gamekeydown));
     joyxmove = joyymove = joystrafemove = joylook = 0;
     mousex = mousey = 0;
```

**Comment by JNechaevsky** [comment]
No, placing this code beneath `// clear cmd building stuff` does not working, matters no if it's just `if (paused)` or `if (paused && musicVolume)` - next level is loaded with locked up note (I have disabled my fix of proper pausing intermission screen for testing).

Also, I belive that `musicVolume` is not necessary here, because we already have an addition, that calls `S_ResumeSound` in `S_SetMusicVolume`, i.e. when next level is loaded and we're chaning music volume, music automatically resume playing. Plus, we can hear first musical note, which is meaning that music is already started, by locked up by pseudo-pause.

Let's investigate it a little bit deeper before PR.

**Comment by fabiangreffrath** [comment]
Perfect, you have a lot more clue about that than I have.

I would probably just copy the relevant block of code from `G_InitNew()` to `G_DoLoadLevel()` then.

**Comment by JNechaevsky** [comment]
Same I did following your recommendation. :) Now waiting for your "green light" about making a PR for Choco.

**Comment by fabiangreffrath** [comment]
Well then :green_heart: 

Let's wait for some days for the request to age in the Choco tracker before I merge it. ;)

**Comment by JNechaevsky** [comment]
Sure, whatever you say. Good thing it will be a PR, not an issue that may fall into oblivion, just like many other issues. :\

**Comment by fragglet** [comment]
Yeah sorry, I haven't been able to dedicate much time to Chocolate Doom lately. I'm very busy at work and just haven't had the time. It's as much as I can manage to take a look at PRs and occasionally comment on things.

I'm a bit surprised that you filed this here (and had the conversation here) knowing that it's a Chocolate Doom bug. It gives the impression like you're scared to post there (??) I really hope that you haven't got some kind of bad impression that's putting you off contributing to Chocolate Doom.

Please do feel free to drop me an email if you'd prefer to discuss it more privately.

**Comment by JNechaevsky** [comment]
Dear @fragglet,

Please, don't get me wrong, there is nothing wrong or scaring me, and I'm gladly explain it openly.

There are few reasons why I'm always preferring to have an approval or discussion before making any kind of pull request, or putting my hands to the other projects:

**1.** I can reproduce many bugs, can deeply test them, can suggest why they are happening and what's causing them, but mostly never - make a perfectly technical correct fix. Not a workaround, but really correct fix. There are always couple of different ways of solving some stuff, but there is also have to be (ideally) exactly one, proper solution.

**2.** My project gone far from just a translation and I can make some mess in the code or simply implement some ideas, which I still generating sometimes, but before sharing them, discussion is always necessary, and the reason of that - Philosophy of other's author.

For example, I know Chocolate Philosophy, I'm collaborating a lot with Fabian and know Crispy Philosophy and know what should I suggest as an Idea and what should not. Exceptions are sometimes happening of course, which is only meaning that discussions are always necessary, But understanding some "nominal fundamentals" will never let me suggest something like "hey, let's make an optional high resolution textures or other _cool_ stuff, but let's just make it optional, let the people choose!".

Yeah, it may sounds oddly conservative, but those four lines in Chocolate commit are not perfectly fitting into Chocolate Philosophy. It's a safe and working approach, but initially something seems to be wrong in another thing like sound library, and this is too hard for me to investigate. Keeping the Chocolate code as close to vanilla as possible is a Chocolate Philosophy, right?

**3.** I'm slightly obsessed by compliance with subordination. Especially with the people, who knows the code much better than me. :)

**4.** I simply don't want to screw up by making a PR with words "hey, it's working, I have checked!".

So yeah, there is nothing wrong or bad. Speaking frankly, of course I'm sad by seeing that Chocolate Doom is not in very active development, despite of there are so many things to investigate in the issues tracker. 

But I'm also understanding such an important things like real life, day job and taking care about family, and more of that - how much time, effort and soul already has been put into the project already. Age is taking it's fee, in both good and bad meanings, but real life should always be preferred.

**Comment by fragglet** [comment]
Thanks for the long and detailed reply. Chocolate Doom obviously has a strict philosophy but the strictness is about the code and not the discussions we have about it. If you're worried some things might not be appropriate to discuss, or of going off-topic, please do not worry- I think we're pretty good about filing bugs in the right place and moving discussions off to the right project when they do go off-topic. All of this ought to be friendly and good-natured, and if you're maybe feeling like aspects of the project philosophy are (unintentionally) oppressive then we ought to fix that. I'd be happy to add something to the PHILOSOPHY doc if it perhaps helps clarify things; I appreciate that its tone is - by design - very restrictive.

Although I pushed back on the PR, I do want to emphasize that I consider both of you to be good friends at this point. If there's any kind of problem you want to discuss then please feel free to contact me. And I know I'm not very active recently but please do feel free to fix and improve things.

**Comment by JNechaevsky** [comment]
Thank you for your kindness as investigation! I'm really appreciate this. :)

You're made an absolutely proper fix and I'm really happy that my suspicions about music code was not very wrong. By very brief testing right before going to the day job, I can confirm that your fix solves issue with OPL. 

But something still not very right with MIDI synth without midiproc presented. Again, I was very short in time before going to day job, but in short words situation is:

- Midiproc is not present
- Native MIDI is chosen
- Level is finished and paused
- Any button pressed and new level is loaded
- No sound and no music at all

After taking a look into Windows sound mixer ([this one](http://priscree.ru/img/722a7d8057ed11.png) as an example), I have noticed that `chocolate-doom.exe` program was having a volume set to `0`. AFAIK, MIDI volume is a Windows-specific bug, and that's why midiproc was introduced. But could this situation in general be related to incorrect unpausing? Obviously, Chocolate Doom is not supposed to run without midiproc, but something still unclear here... Perhaps I will not revert "unpasung" in level loading, but better I check it much more deeply in the evening.

**Comment by JNechaevsky** [comment]
Done all the tests! Just need to render video and post results in https://github.com/chocolate-doom/chocolate-doom/pull/1047, so we don't loose them.
